import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AlertTriangle } from "lucide-react";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Legal Disclaimer | LeasePlain",
  description:
    "LeasePlain's legal disclaimer. Our AI lease analysis is for informational purposes only and does not constitute legal advice.",
  alternates: { canonical: "https://leaseplain.com/disclaimer" },
  openGraph: {
    title: "Legal Disclaimer | LeasePlain",
    description: "LeasePlain's legal disclaimer. Our AI lease analysis is for informational purposes only and does not constitute legal advice.",
    url: "https://leaseplain.com/disclaimer",
    type: "website",
  },
};

export default function DisclaimerPage() {
  return (
    <div className="flex flex-col min-h-full">
      <Navbar />

      <main>
        <section className="bg-slate-50 border-b border-slate-100 py-16 px-4">
          <div className="max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 bg-amber-50 text-amber-700 text-xs font-semibold px-3 py-1.5 rounded-full mb-5 border border-amber-100">
              <AlertTriangle className="w-3.5 h-3.5" aria-hidden="true" />
              Legal Disclaimer
            </div>
            <h1 className="text-4xl font-bold text-slate-900 mb-3">Legal Disclaimer</h1>
            <p className="text-sm text-slate-400">Effective date: May 6, 2026</p>
          </div>
        </section>

        <section className="py-14 px-4 bg-white">
          <div className="max-w-3xl mx-auto space-y-10 text-sm text-slate-700 leading-relaxed">

            <div className="bg-amber-50 border border-amber-100 rounded-xl p-6">
              <h2 className="text-lg font-bold text-amber-900 mb-3">Not Legal Advice</h2>
              <p className="text-amber-800 leading-relaxed">
                LeasePlain is not a law firm and does not provide legal advice. The analysis,
                summaries, explanations, and other content generated by LeasePlain are for
                <strong> informational and educational purposes only</strong>. Nothing on this
                website or in any LeasePlain report constitutes legal advice, and no attorney-client
                relationship is created through your use of the service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">1. No Attorney-Client Relationship</h2>
              <p>
                Use of LeasePlain does not create an attorney-client relationship between you and
                LeasePlain, its operators, or any person or entity associated with LeasePlain.
                The information provided is general in nature and may not apply to your specific
                circumstances.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">2. Informational Purposes Only</h2>
              <p className="mb-3">
                The content generated by our AI — including lease summaries, red flag identifications,
                clause explanations, and questions to ask your landlord — is intended to help you
                understand your lease more easily. It is not:
              </p>
              <ul className="list-disc list-inside space-y-2">
                <li>A legal opinion on any clause in your lease</li>
                <li>A guarantee of accuracy for your specific legal situation</li>
                <li>A substitute for advice from a licensed lawyer or paralegal</li>
                <li>A representation that any clause is or is not enforceable in your jurisdiction</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">3. Consult a Professional</h2>
              <p>
                Before making any legal decision — including signing, refusing to sign, or attempting
                to break a lease — you should consult a licensed lawyer, paralegal, or other qualified
                legal professional in your jurisdiction. If you cannot afford legal advice, contact
                your local legal aid organization.
              </p>
              <p className="mt-3">
                In Ontario, free or subsidized legal assistance may be available through:
              </p>
              <ul className="list-disc list-inside space-y-1.5 mt-2">
                <li>Legal Aid Ontario — legalaid.on.ca</li>
                <li>Community Legal Education Ontario (CLEO) — cleo.on.ca</li>
                <li>Your local community legal clinic</li>
                <li>Tenant Duty Counsel at LTB hearings</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">4. Accuracy of AI Analysis</h2>
              <p>
                Our AI is designed to accurately identify and explain common lease clause types.
                However, AI can and does make mistakes. Analysis results may contain errors,
                omissions, or misinterpretations — particularly for leases with unusual language,
                complex structures, or jurisdiction-specific provisions we have not fully accounted for.
                Always read your original lease and verify our analysis against the actual text.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">5. Jurisdiction</h2>
              <p>
                Our red flag analysis and legal context are strongest for Ontario, Canada — primarily
                referencing the <em>Residential Tenancies Act, 2006</em>. For leases in other
                provinces or countries, the legal analysis may be less accurate. Laws governing
                residential tenancies vary significantly by jurisdiction.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">6. No Liability for Decisions Made</h2>
              <p>
                LeasePlain is not liable for any decisions you make — or fail to make — based on
                the information we provide. This includes decisions about signing, not signing,
                breaking, or renegotiating a lease. You are responsible for independently verifying
                any information and for obtaining appropriate professional advice.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold text-slate-900 mb-3">7. Questions</h2>
              <p>
                If you have questions about this disclaimer or the nature of our service, please
                contact us at{" "}
                <a href="mailto:legal@leaseplain.com" className="text-blue-600 hover:underline">
                  legal@leaseplain.com
                </a>{" "}
                or visit our{" "}
                <Link href="/faq" className="text-blue-600 hover:underline">FAQ page</Link>.
              </p>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
